# Generated by Django 4.2.1 on 2023-05-13 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payment_due', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='clients.client')),
                ('sales_contact', models.ForeignKey(blank=True, limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contract',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('contract', models.OneToOneField(limit_choices_to={'status': 'True'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.contract')),
            ],
            options={
                'ordering': ['-contract__id'],
            },
        ),
    ]
