# Generated by Django 4.2.1 on 2023-05-13 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_contract_contractstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_client', to='clients.client')),
                ('event_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='clients.contractstatus')),
                ('support_contact', models.ForeignKey(blank=True, limit_choices_to={'role': 'support'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('event_status', 'name'), name='unique_event'),
        ),
    ]
